### PR TITLE
switch to system/git and improve find

### PR DESCRIPTION
**Pull request by fearthecowboy**
Changes the id of the git tool to `system/git` and makes some small fixes to searching.

### CODE REVIEW

**Comment by BillyONeal** [comment]
This appears to be looking for an artifact that does not exist?

**Comment by BillyONeal** [comment]
This appears to be looking for an artifact that does not exist?

**Comment by fearthecowboy** [comment]
I'm pulling this into my other branch because it needs registry artifact changes too.

**Comment by fearthecowboy** [comment]
I'm pulling this into my other branch because it needs registry artifact changes too.

**Pull request closed without merging**
